//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registro.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRegistro")]
    public interface IRegistro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/guardar", ReplyAction="http://tempuri.org/IRegistro/guardarResponse")]
        void guardar(int a, string b, string c, string d, int e, string f, string g, string h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/guardar", ReplyAction="http://tempuri.org/IRegistro/guardarResponse")]
        System.Threading.Tasks.Task guardarAsync(int a, string b, string c, string d, int e, string f, string g, string h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/buscar", ReplyAction="http://tempuri.org/IRegistro/buscarResponse")]
        string[] buscar(int cla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/buscar", ReplyAction="http://tempuri.org/IRegistro/buscarResponse")]
        System.Threading.Tasks.Task<string[]> buscarAsync(int cla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/mostrar", ReplyAction="http://tempuri.org/IRegistro/mostrarResponse")]
        string[] mostrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/mostrar", ReplyAction="http://tempuri.org/IRegistro/mostrarResponse")]
        System.Threading.Tasks.Task<string[]> mostrarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/borrar", ReplyAction="http://tempuri.org/IRegistro/borrarResponse")]
        bool borrar(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/borrar", ReplyAction="http://tempuri.org/IRegistro/borrarResponse")]
        System.Threading.Tasks.Task<bool> borrarAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/editar", ReplyAction="http://tempuri.org/IRegistro/editarResponse")]
        bool editar(int a, string b, string c, string d, int e, string f, string g, string h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistro/editar", ReplyAction="http://tempuri.org/IRegistro/editarResponse")]
        System.Threading.Tasks.Task<bool> editarAsync(int a, string b, string c, string d, int e, string f, string g, string h);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistroChannel : Registro.ServiceReference1.IRegistro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistroClient : System.ServiceModel.ClientBase<Registro.ServiceReference1.IRegistro>, Registro.ServiceReference1.IRegistro {
        
        public RegistroClient() {
        }
        
        public RegistroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void guardar(int a, string b, string c, string d, int e, string f, string g, string h) {
            base.Channel.guardar(a, b, c, d, e, f, g, h);
        }
        
        public System.Threading.Tasks.Task guardarAsync(int a, string b, string c, string d, int e, string f, string g, string h) {
            return base.Channel.guardarAsync(a, b, c, d, e, f, g, h);
        }
        
        public string[] buscar(int cla) {
            return base.Channel.buscar(cla);
        }
        
        public System.Threading.Tasks.Task<string[]> buscarAsync(int cla) {
            return base.Channel.buscarAsync(cla);
        }
        
        public string[] mostrar() {
            return base.Channel.mostrar();
        }
        
        public System.Threading.Tasks.Task<string[]> mostrarAsync() {
            return base.Channel.mostrarAsync();
        }
        
        public bool borrar(int a) {
            return base.Channel.borrar(a);
        }
        
        public System.Threading.Tasks.Task<bool> borrarAsync(int a) {
            return base.Channel.borrarAsync(a);
        }
        
        public bool editar(int a, string b, string c, string d, int e, string f, string g, string h) {
            return base.Channel.editar(a, b, c, d, e, f, g, h);
        }
        
        public System.Threading.Tasks.Task<bool> editarAsync(int a, string b, string c, string d, int e, string f, string g, string h) {
            return base.Channel.editarAsync(a, b, c, d, e, f, g, h);
        }
    }
}
